version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/symfony
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/symfony
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: postgres:13-alpine
    container_name: database
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:

